/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-03-14 at 02:45:10 UTC 
 * Modify at your own risk.
 */

package com.example.entity.eventendpoint.model;

/**
 * Model definition for Event.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the eventendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Event extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long downVotes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double eventLat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double eventLong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Date eventTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key ownerId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long upVotes;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDownVotes() {
    return downVotes;
  }

  /**
   * @param downVotes downVotes or {@code null} for none
   */
  public Event setDownVotes(java.lang.Long downVotes) {
    this.downVotes = downVotes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventDescription() {
    return eventDescription;
  }

  /**
   * @param eventDescription eventDescription or {@code null} for none
   */
  public Event setEventDescription(java.lang.String eventDescription) {
    this.eventDescription = eventDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getEventLat() {
    return eventLat;
  }

  /**
   * @param eventLat eventLat or {@code null} for none
   */
  public Event setEventLat(java.lang.Double eventLat) {
    this.eventLat = eventLat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getEventLong() {
    return eventLong;
  }

  /**
   * @param eventLong eventLong or {@code null} for none
   */
  public Event setEventLong(java.lang.Double eventLong) {
    this.eventLong = eventLong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventName() {
    return eventName;
  }

  /**
   * @param eventName eventName or {@code null} for none
   */
  public Event setEventName(java.lang.String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Date getEventTime() {
    return eventTime;
  }

  /**
   * @param eventTime eventTime or {@code null} for none
   */
  public Event setEventTime(Date eventTime) {
    this.eventTime = eventTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventType() {
    return eventType;
  }

  /**
   * @param eventType eventType or {@code null} for none
   */
  public Event setEventType(java.lang.String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Event setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getOwnerId() {
    return ownerId;
  }

  /**
   * @param ownerId ownerId or {@code null} for none
   */
  public Event setOwnerId(Key ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUpVotes() {
    return upVotes;
  }

  /**
   * @param upVotes upVotes or {@code null} for none
   */
  public Event setUpVotes(java.lang.Long upVotes) {
    this.upVotes = upVotes;
    return this;
  }

  @Override
  public Event set(String fieldName, Object value) {
    return (Event) super.set(fieldName, value);
  }

  @Override
  public Event clone() {
    return (Event) super.clone();
  }

}
